---
title: "Fitting AcceleratingHT Model to CGD Model"
output: 
  html_notebook:
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
library(magrittr)
library(tidyverse)
library(R6)
library(kableExtra)

library(vaccineEarlyInvest)

source("model_fit_util.R")

knitr::opts_chunk$set(fig.width = 9)
```

```{r load-data}
cgd_optim_data <- bind_rows(
  "Normal" = read_rds(file.path("data", "cgd_optim.rds")),
  
  .id = "optim_type" 
) %>% 
  nest(model_data = -optim_type) 

cgd_id_dict <- read_rds(file.path("data", "cgd_id_dict.rds")) %>% 
  group_by(Platform, Subcategory, phase) %>% 
  mutate(vacc_type_id = cur_group_id()) %>% 
  ungroup()
```

```{r baseline-aht-model}
maxcand <- 75

baseline_model_success_rates <- lst(
  "Normal" = file.path("data", "cgd_optim_aht_vaccines.csv")
) %>% 
  map(load_candidate_data) %>% 
  map(~ get_candidate_draws(
    candidate_data = .x, 
    dordered = calc_dordered(.x, maxcand = maxcand),
    replications = 100e3, 
    maxcand = maxcand,
    group_vaccines_by = NULL 
  )) %>% 
  map(get_summary_success_rates) %>% 
  map(right_join, select(cgd_id_dict, vacc_group_id = candInd, cgd_vaccine_id, vacc_type_id), by = "vacc_group_id") %>% 
  enframe(name = "optim_type", value = "baseline_success_rate")

cgd_optim_data %<>% 
  left_join(baseline_model_success_rates, by = "optim_type")
```


```{r plot-functions}
plot_model_param <- function(optim_data, .baseline_param = baseline_param) {
  baseline_param_data <- .baseline_param %>% 
    enframe(name = "param_name", value = "param_val")
  
  optim_data %>% 
    select(run_id, month, param_data) %>% 
    unnest(param_data) %>%
    group_by(run_id, month) %>% 
    filter(step == max(step)) %>% 
    ungroup() %>% 
    select(!c(obj, summary)) %>%  
    pivot_longer(., -c(step, run_id, month), names_to = "param_name", values_to = "param_val") %>% 
    ggplot() +
    geom_hline(aes(yintercept = param_val), linetype = "dashed", 
               data = . %>% 
                 modelr::data_grid(param_name, month) %>% 
                 left_join(baseline_param_data, by = "param_name")) +
    geom_line(aes(month, param_val, group = run_id), alpha = 0.5, color = "darkred") +
    scale_x_date("", breaks = "2 months", labels = scales::date_format("%m/%y")) +
    labs(
      title = "Parameter Fit", 
      y = "",
      caption = "Dashed horizontal line: baseline AHT model parameters."
    ) +
    facet_wrap(vars(param_name)) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    NULL
}

plot_success_rates <- function(optim_data, baseline_success_rate) {
  optim_data %>% 
    ggplot(aes(month, success_rate)) +
    geom_hline(aes(yintercept = success_rate), linetype = "dashed",
               data = baseline_success_rate %>% 
                 distinct(cgd_vaccine_id, .keep_all = TRUE)) +
    geom_line(
      data = . %>%
        distinct(month, .keep_all = TRUE) %>%
        select(month, cgd_summary) %>%
        rowwise() %>%
        mutate(cgd_summary = list(cgd_summary$success_rates)) %>%
        ungroup() %>%
        unnest(cgd_summary) %>% 
        left_join(cgd_id_dict, by = c("vacc_group_id" = "candInd")) %>% 
        arrange(cgd_vaccine_id)
    ) +
    geom_line(
      aes(group = run_id), alpha = 0.5, color = "darkred",
      data = . %>%
        rowwise() %>%
        mutate(run_summary = list(semi_join(run_summary$success_rates, cgd_summary$success_rates, by = "vacc_group_id"))) %>%
        ungroup() %>%
        select(run_id, month, run_summary) %>%
        unnest(run_summary) %>% 
        left_join(cgd_id_dict, by = c("vacc_group_id" = "candInd")) %>% 
        arrange(cgd_vaccine_id)
    ) +
    scale_x_date("", breaks = "2 months", labels = scales::date_format("%m/%y")) +
    labs(title = "Success Probability By Vaccine Candidate",
         subtitle = "Restricted to phase 2 and 3 vaccines.",
         caption = "Using 5 runs.
                    Solid black line: the moment calculated from the CGD model data.
                    Dashed horizontal line: baseline AHT model parameters.",
         y = ""
       ) +
    facet_wrap(
      vars(cgd_vaccine_id),
      labeller = labeller(
        cgd_vaccine_id = function(ids) {
          left_join(tibble(cgd_vaccine_id = as.integer(ids)), cgd_id_dict, by = c("cgd_vaccine_id")) %$%
            str_glue("CGD ID: {cgd_vaccine_id}\n{Platform}\n{Subcategory}\n{phase}") %>%
            as.character()
        }
      )
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    NULL
}

plot_vacc_type_success_rates <- function(optim_data, baseline_sucess_rate) {
  optim_data %>% 
    ggplot(aes(month, success_rate)) +
    geom_hline(aes(yintercept = success_rate), linetype = "dashed",
               data = baseline_sucess_rate %>% 
                 group_by(vacc_type_id) %>% 
                 summarize(success_rate = mean(success_rate), .groups = "drop")) +
    geom_line(
      aes(group = run_id), alpha = 0.5, color = "darkred",
      data = . %>%
        rowwise() %>%
        mutate(run_summary = list(semi_join(run_summary$success_rates, cgd_summary$success_rates, by = "vacc_group_id"))) %>%
        ungroup() %>%
        select(run_id, month, run_summary) %>%
        unnest(run_summary) %>% 
        left_join(cgd_id_dict, by = c("vacc_group_id" = "candInd")) %>% 
        distinct(run_id, month, vacc_type_id, .keep_all = TRUE)
    ) +
    geom_line(
      data = . %>%
        filter(run_id == 1) %>%
        select(month, cgd_summary) %>%
        rowwise() %>%
        mutate(cgd_summary = list(cgd_summary$success_rates)) %>%
        ungroup() %>%
        unnest(cgd_summary) %>% 
        left_join(cgd_id_dict, by = c("vacc_group_id" = "candInd")) %>% 
        group_by(month, vacc_type_id) %>% 
        summarize(success_rate = mean(success_rate), .groups = "drop")
    ) +
    scale_x_date("", breaks = "2 months", labels = scales::date_format("%m/%y")) +
    labs(title = "Success Probability By Platform-Subcategory-Phase",
         subtitle = "Restricted to phase 2 and 3 vaccines.",
         caption = "Using 5 runs.
                    Solid black line: the moment calculated from the CGD model data.
                    Dashed horizontal line: baseline AHT model parameters.",
         y = ""
    ) +
    facet_wrap(
      vars(vacc_type_id),
      labeller = labeller(
        vacc_type_id = function(ids) {
          left_join(tibble(vacc_type_id = as.integer(ids)), 
                    distinct(cgd_id_dict, vacc_type_id, Platform, Subcategory, phase), 
                    by = c("vacc_type_id")) %$%
            str_glue("{Platform}\n{Subcategory}\n{phase}") %>%
            as.character()
        }
      )
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    NULL
}
```

Using 10 simulation runs.

```{r param-plot}
cgd_optim_data %$% 
  map(set_names(model_data, optim_type), plot_model_param) %>% {
    cowplot::plot_grid(
      plotlist = imap(., ~ .x + labs(subtitle = .y)) %>% 
        map_if(c(FALSE, rep(TRUE, max(0, length(.) - 1))), ~ .x + labs(title = "")), 
      ncol = 1)
  }
```

```{r candidates-table}
cgd_id_dict %>%
  arrange(cgd_vaccine_id) %>% 
  select(
    cgd_vaccine_id, name, institutes, country, Platform, Subcategory, firm_size, funding, phase) %>%
  mutate_at(vars(name, institutes, country), str_replace_all , "/", "<br>") %>% 
  kbl(
    col.names = c("CGD ID", "Name", "Institutes", "Country", "Platform", "Subcategory", "Firm Size", "Funding", "Phase"), 
    escape = FALSE, 
    caption = "Restricted to phase 2 and 3 vaccines." 
  ) %>% 
  kable_styling()
```

```{r success-prob-by-candidate, fig.height=9}
cgd_optim_data %$% 
  map2(set_names(model_data, optim_type), baseline_success_rate, plot_success_rates) %>% {
    cowplot::plot_grid(
      plotlist = imap(., ~ .x + labs(subtitle = .y)) %>% 
        map_if(c(FALSE, rep(TRUE, max(0, length(.) - 1))), ~ .x + labs(title = "")), 
      ncol = 1
    )
  }
```

```{r success-prob-by-type, fig.height=7}
cgd_optim_data %$% 
  map2(set_names(model_data, optim_type), baseline_success_rate, plot_vacc_type_success_rates) %>% {
    cowplot::plot_grid(
      plotlist = imap(., ~ .x + labs(subtitle = .y)) %>% 
        map_if(c(FALSE, rep(TRUE, max(0, length(.) - 1))), ~ .x + labs(title = "")), 
      ncol = 1
    )
  }
```
